@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/signup
Content-Type: application/application/json
Accept: application/json
withCredentials: true

{
  "username": "danny",
  "password": "qwerty",
  "email": "dan@gte.pl",
  "avatarColor": "red",
  "avatarImage": "red",
}
